development:
  access_key_id: 123...
  secret_access_key: 123...
test:
  access_key_id: abc...
  secret_access_key: abc...
production:
  access_key_id: AKIAJUUJHZDLCYXBQ3YA
  secret_access_key: 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
