# Generated by cucumber_scaffold - http://github.com/andyw8/cucumber_scaffold

Feature: Manage club teams
  In order to [goal]
  [stakeholder]
  wants [behaviour]

    Scenario: List all club teams
      Given the following club teams:
        | name | information | slug | parent id | position | 
        | name 1 | information 1 | slug 1 | 11 | 11 | 
        | name 2 | information 2 | slug 2 | 12 | 12 | 
        | name 3 | information 3 | slug 3 | 13 | 13 | 
      When I go to the club teams page
      Then I should see the following club teams:
        | Name | Information | Slug | Parent id | Position | 
        | name 1 | information 1 | slug 1 | 11 | 11 | 
        | name 2 | information 2 | slug 2 | 12 | 12 | 
        | name 3 | information 3 | slug 3 | 13 | 13 |
      And the heading should be "Listing club_teams"
      

    Scenario: View a club team
      Given the following club teams:
        | name | information | slug | parent id | position |
        | name 1 | information 1 | slug 1 | 11 | 11 | 
        | name 2 | information 2 | slug 2 | 12 | 12 |
        | name 3 | information 3 | slug 3 | 13 | 13 |
      When I go to the club teams page
      And I click "Show" in the 2nd row
      Then I should see the following club team:
        | Name: | name 2 |
        | Information: | information 2 |
        | Slug: | slug 2 |
        | Parent: | 12 |
        | Position: | 12 |
                  
      When I follow "Back"
      
      Then I should be on the club teams page

    Scenario: Edit a club team
      Given the following club team:
        | name | name 10 |
        | information | information 10 |
        | slug | slug 10 |
        | parent_id | 20 |
        | position | 20 |
      When I go to the page for that club team
      And I follow "Edit"
      Then I should see the following form field values:
        | Name | name 10 |
        | Information | information 10 |
        | Slug | slug 10 |
        | Parent | 20 |
        | Position | 20 |
      Then the heading should be "Editing club_team"
      
      When I follow "Show"
      Then I should be on the page for that club team

    Scenario: Delete a club team via the index page
      Given the following club teams:
        | name | information | slug | parent id | position | 
        | name 1 | information 1 | slug 1 | 11 | 11 | 
        | name 2 | information 2 | slug 2 | 12 | 12 | 
        | name 3 | information 3 | slug 3 | 13 | 13 |
      When I go to the club teams page
      And I click "Destroy" in the 2nd row
      Then I should see the following club teams:
        | Name | Information | Slug | Parent id | Position | 
        | name 1 | information 1 | slug 1 | 11 | 11 | 
        | name 3 | information 3 | slug 3 | 13 | 13 |
      And I should be on the club teams page
      
    
    Scenario: New club team page  
      Given I am on the club teams page
      When I follow "New Club team"
      Then I should be on the new club team page
      
      When I follow "Back"
      Then I should be on the club teams page

    Scenario: Create a new club team
      Pending
      # Given I am on the new club team page
      # When I fill in the form with:
      #   | Name | name 10 |
        # | Information | information 10 |
        # | Slug | slug 10 |
        # | Parent | 20 |
        # | Position | 20 |
      # And I press "Create"
      # Then I should see "Club team was successfully created."
      # And I should see the following club team:
      #   | Name: | name 10 |
        # | Information: | information 10 |
        # | Slug: | slug 10 |
        # | Parent: | 20 |
        # | Position: | 20 |

    Scenario: Attempt to create a new club team with invalid input
      Pending
      # You should use this scenario as the basis for scenarios involving ActiveRecord validations, or delete it if it's not required
      # Given I am on the new club team page
      # When I fill in the form with:
      #   | Name | name 10 |
        # | Information | information 10 |
        # | Slug | slug 10 |
        # | Parent | 20 |
        # | Position | 20 |
      # And I press "Create"
      # Then I should see "1 error prohibited this club_team from being saved:"
      #
      # [You should add checks for specific errors here. It may be appropriate to add extra scenarios.]
      #
      # And I should see the following form field values:
      #   | Name | name 10 |
        # | Information | information 10 |
        # | Slug | slug 10 |
        # | Parent | 20 |
        # | Position | 20 |

    Scenario: Attempt to update a club team with invalid input
      Pending
      # You should use this scenario as the basis for scenarios involving ActiveRecord validations, or delete it if it's not required
      # Given a club team exists
      # When I go to the edit page for that club team
      # And I fill in the form with:
      #   | Name | name 10 |
        # | Information | information 10 |
        # | Slug | slug 10 |
        # | Parent | 20 |
        # | Position | 20 |
      # And I press "Update"
      # Then I should see "1 error prohibited this club_team from being saved:"
      #
      # [You should add checks for specific errors here. It may be appropriate to add extra scenarios.]
      #
      # And I should see the following form field values:
      #   | Name | name 10 |
        # | Information | information 10 |
        # | Slug | slug 10 |
        # | Parent | 20 |
        # | Position | 20 |

    Scenario: Update a club team
      Given the following club team:
        | name | name 10 |
        | information | information 10 |
        | slug | slug 10 |
        | parent_id | 20 |
        | position | 20 |
      When I go to the edit page for that club team
      And I fill in the form with:
        | Name | name 10 updated |
        | Information | information 10 updated |
        | Slug | slug 10 updated |
        | Parent | -20 |
        | Position | -20 | 
      And I press "Update"
      Then I should be on the page for that club team
      And I should see "Club team was successfully updated."
      And I should see the following club team:
        | Name: | name 10 updated |
        | Information: | information 10 updated |
        | Slug: | slug 10 updated |
        | Parent: | -20 |
        | Position: | -20 |

    Scenario: Navigate from club teams page to the edit club team page
      Given the following club teams:
        | name | information | slug | parent id | position | 
        | name 1 | information 1 | slug 1 | 11 | 11 | 
        | name 2 | information 2 | slug 2 | 12 | 12 | 
        | name 3 | information 3 | slug 3 | 13 | 13 |
      When I go to the club teams page
      And I click "Edit" in the 2nd row
      Then I should be on the edit page for the 2nd club team

    Scenario: Navigate from edit club team page to the club teams page
      Given a club team exists
      When I go to the edit page for that club team
      And I follow "Back"
      Then I should be on the club teams page